version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "3000:3000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "87:87"
    depends_on:
      - django_gunicorn

volumes:
  static:

