# Generated by Django 4.0.7 on 2022-09-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('num_envoi', models.CharField(db_column='numEnvoi', max_length=50, primary_key=True, serialize=False)),
                ('bureau_ori', models.CharField(db_column='bureauOri', max_length=50)),
                ('bureau_exp', models.CharField(db_column='bureauExp', max_length=50)),
                ('bureau_dest', models.CharField(db_column='bureauDest', max_length=50)),
                ('bureau_pass', models.CharField(db_column='bureauPass', max_length=50))
            ],
        ),
        migrations.CreateModel(
            name='TblBureau',
            fields=[
                ('ncodique', models.IntegerField(db_column='NCODIQUE', primary_key=True, serialize=False)),
                ('bureau', models.CharField(db_column='Nombureau', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True)
        ),
    ]
