# Generated by Django 4.1.1 on 2022-10-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidaapp', '0002_envoi_tblbureau_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoi',
            name='poids',
            field=models.DecimalField(blank=True, db_column='poids', decimal_places=2, max_digits=3, null=True)
        ),
    ]
