# Generated by Django 4.0.8 on 2023-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidaapp', '0004_remove_envoi_poids'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoi',
            name='poids',
            field=models.DecimalField(blank=True, db_column='poids', decimal_places=2, max_digits=3, null=True),
        ),
    ]
