# Generated by Django 4.0.10 on 2023-10-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapidaapp', '0005_envoi_poids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('idPers', models.IntegerField(db_column='idPers', primary_key=True, serialize=False)),
                ('mail', models.CharField(db_column='mail', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidaapp.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rapidaapp.user')),
            ],
        ),
    ]
